### ISSUE TITLE
ERR_PACKAGE_PATH_NOT_EXPORTED @babel/helper-compilation-targets

### ISSUE THREAD

**Issue by crrmacarse** [crrmacarse/portfolio-remake#7]
CI Crash

```
    at Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Object.newLoader [as .js] (/home/runner/work/crrmacarse.github.io/crrmacarse.github.io/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (/home/runner/work/crrmacarse.github.io/crrmacarse.github.io/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/home/runner/work/crrmacarse.github.io/crrmacarse.github.io/node_modules/@babel/preset-env/lib/index.js:11:14)
    at Module._compile (/home/runner/work/crrmacarse.github.io/crrmacarse.github.io/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Module._compile (/home/runner/work/crrmacarse.github.io/crrmacarse.github.io/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Object.newLoader [as .js] (/home/runner/work/crrmacarse.github.io/crrmacarse.github.io/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (/home/runner/work/crrmacarse.github.io/crrmacarse.github.io/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at requireModule (/home/runner/work/crrmacarse.github.io/crrmacarse.github.io/node_modules/@babel/core/lib/config/files/plugins.js:165:12)
    at loadPreset (/home/runner/work/crrmacarse.github.io/crrmacarse.github.io/node_modules/@babel/core/lib/config/files/plugins.js:83:17)
    at createDescriptor (/home/runner/work/crrmacarse.github.io/crrmacarse.github.io/node_modules/@babel/core/lib/config/config-descriptors.js:154:9)
    at /home/runner/work/crrmacarse.github.io/crrmacarse.github.io/node_modules/@babel/core/lib/config/config-descriptors.js:109:50
    at Array.map (<anonymous>) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

Error link: https://github.com/crrmacarse/crrmacarse.github.io/runs/1139434347?check_suite_focus=true

Stackoverflow link: https://stackoverflow.com/questions/62246824/error-err-package-path-not-exported-no-exports-main-resolved-in-app-node-m

**Comment by crrmacarse** [comment]
Fix for this issue

```
npm install @babel/helper-compilation-targets --save-dev
```
